@host=http://localhost:5021
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCYW5hbmFEaW5uZXIuRG9tYWluLlVzZXJBZ2dyZWdhdGUuVmFsdWVPYmplY3RzLlVzZXJJZCIsImp0aSI6ImNjOTgyYTQ2LTE0OGUtNDcyZC1hY2I2LWFiZDUwYzgyNWRiZCIsImdpdmVuX25hbWUiOiJIZW5yaXF1ZSIsImZhbWlseV9uYW1lIjoiTWFycXVlcyIsImV4cCI6MTcyNDcyNTIyMSwiaXNzIjoiQmFuYW5hRGlubmVyIiwiYXVkIjoiQmFuYW5hRGlubmVyIn0.4k4-4ZsyoJjHepmutOXNFXOPF_wAt8cCeUKzA2K0Djw
@hostId=teste
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": { "value": "00000000-0000-0000-0000-000000000000" },
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "averageRating": 4.5,
    "sections": [
        {
            "id": { "value": "00000000-0000-0000-0000-000000000000" },
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "id": { "value": "00000000-0000-0000-0000-000000000000" },
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ],
    "hostId": { "value": "00000000-0000-0000-0000-000000000000" },
    "dinnerIds": [
        { "value": "00000000-0000-0000-0000-000000000000" }
    ],
    "menuReviewIds": [
        { "value": "00000000-0000-0000-0000-000000000000" }
    ],
    "createdDateTime": "2020-01-01T00:00:00.0000000Z",
    "updatedDateTime": "2020-01-01T00:00:00.0000000Z"
}